[package]
name = "micromzpaf"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

# Workspace-inherited deps
rustyms = { workspace = true }
